### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by PraveenPal4232** [PraveenPal4232/learnthatyourself#1]
Hello @coryhouse
I am facing an error "TypeError: Cannot read property 'map' of undefined" when I am trying to map
"{this.props.courses.map((course) => (
<div key="{course.title}">{course.title}</div>
))}"
in CoursePage.js in 9: Redux Flow > Step through Redux Flow and Try Redux DevTools
I googled it, but I doesn't work for me. Do you have any Idea, please help me out?

**Comment by coryhouse** [comment]
You're sending course instead of courses [here](https://github.com/PraveenPal4232/learnthatyourself/blob/master/src/redux/actions/courseAction.js#L9).

And your course reducer doesn't match the course. It should be:

    case types.LOAD_COURSES_SUCCESS:
      return action.courses;
